language: node_js
node_js:
- stable
addons:
  ssh_known_hosts: course-scheduler.me
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_94466d3b2c72_key -iv $encrypted_94466d3b2c72_iv
  -in deploy-key.enc -out deploy-key -d
- rm deploy-key.enc
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
script:
- npm run prod
after_success:
- bash scripts/deploy.sh
