language: node_js
node_js:
- stable
addons:
  ssh_known_hosts: course-scheduler.me
cache:
  directories:
  - node_modules
before_install:
- bash scripts/before_install.sh
script:
- npm run prod
after_success:
- bash scripts/deploy.sh
