export const DraftConstants = {
    ADD_TO_DRAFT: 'ADD_TO_DRAFT',
    REMOVE_FROM_DRAFT: 'REMOVE_FROM_DRAFT',
    FETCH_DRAFT: 'FETCH_DRAFT',
    SET_LOCKED_GROUPS: 'SET_LOCKED_GROUPS',
    UPDATE_DRAFT_COURSE: 'UPDATE_DRAFT_COURSE'
};