export const RegisteredCoursesConstants = {
    ADD_TO_REGISTERED_COURSES: 'ADD_TO_REGISTERED_COURSES',
    FETCH_REGISTERED_COURSES: 'FETCH_REGISTERED_COURSES',
    REMOVE_FROM_REGISTERED_COURSES: 'REMOVE_FROM_REGISTERED_COURSES'
};