export const SearchConstants = {
    SEARCH_COURSES: 'SEARCH_COURSES',
    CHANGE_SEARCH_FILTER: 'CHANGE_SEARCH_FILTER',
    CHANGE_DETAILED_SEARCH_FILTERS: 'CHANGE_DETAILED_SEARCH_FILTERS',
    CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS'
};